// Shared contract for the CPI prototype. Implements the data model of
// design-xxx/SPEC-CPI.md. Owned by the manager: workers do not edit this file.

// ---------------------------------------------------------------------------
// Source positions and trace sites
// ---------------------------------------------------------------------------

export type Pos = { readonly file: string; readonly line: number; readonly col: number };

// Where an expression sits: the procedure whose body it is in (null at top
// level or in an anonymous lambda) and its source position (null if unknown).
export type Site = { readonly fn: Sym | null; readonly pos: Pos | null };

// ---------------------------------------------------------------------------
// Values (SPEC-CPI section 2)
// ---------------------------------------------------------------------------

export type Sym   = { readonly t: 'sym';   readonly name: string };   // interned: compare with ===
export type Bool  = { readonly t: 'bool';  readonly v: boolean };     // two singletons
export type Nil   = { readonly t: 'nil' };                            // one singleton
export type Int   = { readonly t: 'int';   readonly v: bigint };      // always within signed 64 bits
export type Float = { readonly t: 'float'; readonly v: number };
export type Str   = { readonly t: 'str';   readonly v: string };

// pos is reader metadata only: never part of equality.
export type Pair  = { readonly t: 'pair';  readonly car: Value; readonly cdr: Value; readonly pos: Pos | null };

// A local defun's group member (SPEC-CPI section 7.2).
export type GroupMember = { readonly name: Sym; readonly params: readonly Sym[]; readonly body: readonly Value[] };

export type Closure = {
  readonly t: 'closure';
  readonly name: Sym | null;                   // null for lambda
  readonly params: readonly Sym[];
  readonly body: readonly Value[];             // expanded expressions
  readonly scope: Scope;                       // captured local scope
  readonly group: readonly GroupMember[] | null; // non-null only for local defuns
};

// The context recorded when an error is first thrown (SPEC-CPI sections 2.3, 7.5).
export type ErrorContext = {
  readonly site: Site;    // the throwing expression
  readonly scope: Scope;  // its local scope
  readonly K: Kont;       // the continuation at the throw
  readonly R: Env;        // the thrower's env ref
};

export type ErrorValue = {
  readonly t: 'error';
  readonly tag: Sym;
  readonly message: string;
  readonly payload: Value;
  readonly cause: ErrorValue | null;
  // Write-once: null until the error is first thrown, then set by the machine
  // and never changed. This is the one mutable field on any value.
  readonly box: { ctx: ErrorContext | null };
};

export type Addr   = { readonly t: 'addr'; readonly id: string };
export type Pid    = { readonly t: 'pid';  readonly id: number };
export type EnvRef = { readonly t: 'env';  readonly env: Env };

export type Value = Sym | Bool | Nil | Int | Float | Str | Pair | Closure | ErrorValue | Addr | Pid | EnvRef;

// ---------------------------------------------------------------------------
// Local scopes (SPEC-CPI section 6): a persistent linked list, innermost first.
// ---------------------------------------------------------------------------

export type Scope = { readonly name: Sym; readonly value: Value; readonly next: Scope } | null;

// ---------------------------------------------------------------------------
// Environments (DESIGN-001 section 8): slot algebra.
// ---------------------------------------------------------------------------

export type Slot =
  | { readonly s: 'required';   readonly name: string }
  | { readonly s: 'defined';    readonly name: string; readonly value: Value }
  | { readonly s: 'conflicted'; readonly name: string; readonly left: Slot; readonly right: Slot };

// Insertion-ordered; one slot per name.
export type Env = { readonly slots: ReadonlyMap<string, Slot> };

// ---------------------------------------------------------------------------
// Frames and continuations (SPEC-CPI section 7)
// ---------------------------------------------------------------------------

// What an Args frame is collecting arguments for.
export type Head =
  | { readonly h: 'core'; readonly op: string }                      // core operation
  | { readonly h: 'host'; readonly ns: string; readonly action: string } // ns::action
  | { readonly h: 'call' };                                          // done[0] is the procedure

export type Frame =
  | { readonly k: 'args';  readonly head: Head; readonly done: readonly Value[]; readonly rest: readonly Value[]; readonly scope: Scope; readonly site: Site }
  | { readonly k: 'let';   readonly name: Sym; readonly rest: readonly Value[]; readonly scope: Scope; readonly site: Site }
  | { readonly k: 'seq';   readonly rest: readonly Value[]; readonly scope: Scope; readonly site: Site }
  | { readonly k: 'cond';  readonly body: readonly Value[]; readonly rest: readonly Value[]; readonly scope: Scope; readonly site: Site }
  | { readonly k: 'and';   readonly rest: readonly Value[]; readonly scope: Scope; readonly site: Site }
  | { readonly k: 'or';    readonly rest: readonly Value[]; readonly scope: Scope; readonly site: Site }
  | { readonly k: 'catch'; readonly name: Sym; readonly handler: Value; readonly scope: Scope; readonly site: Site }
  // Resumption frames (SPEC-CPI section 8): each discards the value it receives.
  | { readonly k: 'val';   readonly v: Value }
  | { readonly k: 'throw'; readonly e: ErrorValue }
  | { readonly k: 'eval';  readonly x: Value; readonly scope: Scope; readonly site: Site };

// Persistent list of frames, top first. Pushing makes a new node; nothing is mutated.
export type Kont = { readonly top: Frame; readonly next: Kont } | null;

// ---------------------------------------------------------------------------
// Machine state (SPEC-CPI section 7.1)
// ---------------------------------------------------------------------------

export type Mode =
  | { readonly m: 'eval';   readonly x: Value; readonly scope: Scope; readonly site: Site }
  | { readonly m: 'ret';    readonly v: Value }
  | { readonly m: 'throw';  readonly e: ErrorValue } // e.box.ctx is already set
  | { readonly m: 'host';   readonly ns: string; readonly action: string; readonly args: readonly Value[]; readonly site: Site }
  | { readonly m: 'done';   readonly v: Value }
  | { readonly m: 'failed'; readonly e: ErrorValue };

// The checkpoint slot: the name of the procedure the process was spawned
// with, and the arguments of the most recent call to it.
export type Checkpoint = { readonly name: string | null; readonly args: readonly Value[] };

export type State = { readonly mode: Mode; readonly K: Kont; readonly R: Env; readonly A: Checkpoint };

// ---------------------------------------------------------------------------
// Core operations (SPEC-CPI section 5)
// ---------------------------------------------------------------------------

export type Result = { readonly ok: true; readonly v: Value } | { readonly ok: false; readonly e: ErrorValue };

// fn receives exactly `arity` arguments; the machine checks arity first.
// `apply` is in the table for its name and arity only: the machine handles it
// itself, because applying a closure is a machine transition.
export type CoreOp = { readonly name: string; readonly arity: number; readonly fn: (args: readonly Value[]) => Result };
